# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font:size=12
dpi-aware=yes
icons-enabled=yes
width=150
horizontal-pad=18
vertical-pad=14
inner-pad=10
line-height=16
prompt="/home/thea > "
layer=overlay
terminal=foot

[colors]
background=0f172acc
text=e2e8f0ff
match=7dd3fcff
selection=1e3a5fff
selection-text=f8fafcff
selection-match=bae6fdff
border=60a5faff

[border]
width=2
radius=14

[dmenu]
exit-immediately-if-empty=yes
